In [0]:
import pandas as pd
from google.colab import files
import io
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
from sklearn.metrics import confusion_matrix
import numpy as np

In [6]:
uploaded = files.upload()

Saving iris.csv to iris.csv


In [0]:
base = pd.read_csv(io.BytesIO(uploaded['iris.csv']))

In [0]:
previsores = base.iloc[:,0:4].values # iloc: recorta a base de dados [linhas , colunas] , sendo que o intervalo 0:3 captura as linhas 0,1,2
classe = base.iloc[:,4].values
labelencoder = LabelEncoder() # cria um objeto label encoder, transforma  string em int
classe = labelencoder.fit_transform(classe) # aplica o label encoder
classe_dummy = np_utils.to_categorical(classe) # transforma [1,2,0,2,1,...] em [[0,1,0],[0,0,1],[1,0,0],[0,1,0],...]

In [0]:
previsores_train, previsores_test, classe_train, classe_test = train_test_split(previsores, classe_dummy, test_size=0.25)

In [0]:
classificador = Sequential()
classificador.add(Dense(units=4, activation='relu', input_dim = 4))
classificador.add(Dense(units=4, activation='relu'))
classificador.add(Dense(units=3, activation='softmax')) # um neuronio para cada classe e a funcao tem que ser compatível

In [0]:
classificador.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy']) # tanto a loss fun quanto a precisao precisam ser categoricas

In [0]:
classificador.fit(previsores_train,classe_train,batch_size=10,epochs=1000)

In [23]:
resultado = classificador.evaluate(previsores_test,classe_test)
print(resultado)

38/38 [==============================] - 0s 296us/step
[0.06855578622535656, 0.9736842105263158]


In [0]:
previsoes = classificador.predict(previsores_test)
previsoes = (previsoes > 0.5)

classe_test2 = [np.argmax(t) for t in classe_test] # lendo: pega o maior argumento de t sendo t um elemento de classe_test
previsoes2 = [np.argmax(t) for t in previsoes]# caminho inverso do dummy

In [0]:
matriz = confusion_matrix(previsoes2, classe_test2)

In [30]:
print(matriz)

[[14  0  0]
 [ 0  7  1]
 [ 0  0 16]]
